# Generated by Django 3.1.4 on 2020-12-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20201223_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='favorites_Hotel',
        ),
    ]
